# simple dockerfile to test OCP s2i using Dockerfile 

FROM registry.access.redhat.com/ubi7:latest

# CMD ["/bin/bash", "-c", "sleep infinity 2"]
CMD ["/bin/bash", "-c", "--", "while true; do sleep 29; done;"]
# CMD ["/bin/bash", "-c", "--", "while true; do sleep 12; done;"]
